### ISSUE TITLE
Passing "null" to FlattenString outputs empty JSON object instead of error

### ISSUE THREAD

**Issue by zdebra** [jeremywohl/flatten#10]
See following example: 
```
	flat, err := flatten.FlattenString("null", "", flatten.DotStyle)
	fmt.Printf("error: %v\n", err)
	fmt.Printf("v: %s\n", flat)

	flat, err = flatten.FlattenString("a", "", flatten.DotStyle)
	fmt.Printf("error: %v\n", err)
	fmt.Printf("v: %s\n", flat)
```
https://play.golang.org/p/AKQWQcY_VA6

String literal value is provided in both examples (`"null"` and `"a"`). We got no error for the first case with `{}` value as an output where for the second example the output spawns the error.

I would expect an error.

I know this is an edge case and both behaviors are acceptable. I propose to at least add a test for it. I am happy to contribute once it's clear what to do.

**Comment by jeremywohl** [comment]
Thanks for the corner case.  See the referenced patch, I've restricted FlattenString input to things that look like a JSON map, i.e. begin with a '{'.

This seems like a safe, non-breaking API change since all non-map inputs, except for "null", have produced an error.

Thoughts?

**Comment by zdebra** [comment]
Agree 👍
