### ISSUE TITLE
Flattened map is un-order

### ISSUE THREAD

**Issue by luongdieu86** [jeremywohl/flatten#4]
Hi all,

Is there any option to keep the order of Flattned Map same with origion JSON string ?

**Comment by jeremywohl** [comment]
Do you have an example?

**Comment by xdefrag** [comment]
@luongdieu86 maps in Go by design is unordered, see https://blog.golang.org/go-maps-in-action iteration order part.

**Comment by jeremywohl** [comment]
Yes, if we understand you to mean the resulting Go map type (thanks @xdefrag):

> When iterating over a map with a range loop, the iteration order is not specified and is not guaranteed to be the same from one iteration to the next.

@luongdieu86 Can I close this issue or do we misunderstand your request?
