### ISSUE TITLE
Support for unflattening (e.g. reverse operation)

### ISSUE THREAD

**Issue by aidansteele** [jeremywohl/flatten#9]
Hi,

Nice library! Have you considered adding support for reversing, i.e. unflattening? If I slightly change the example in the README:

```golang
input := `{ "one.two.0": "2a", "one.two.1": "2b", "side": "value" }`
nested, err := flatten.UnflattenString(input, "", flatten.DotStyle)

/*
nested == {
  "one": {
    "two": [
      "2a",
      "2b"
    ]
  },
  "side": "value"
}
*/
```

**Comment by jeremywohl** [comment]
Hmm, we lose information in flattening, would have to name appropriately.

Do you have a specific example use case?

**Comment by leslie-qiwa** [comment]
Unflattening should be useful in such a use case:
1. I need a flattened json string to store all key values.
2. I want to combine multiple sources of data into one json file, then add corresponding prefix for each flattened key. for example, {"facebook.username": "abc", "facebook.userpost": 5, "twitter.username": "xyz", "twitter.userpost": 20, ...}.

Unflattern may help user to reconstruct the struct and ease to operate if unmarshal is needed.
